// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/timer/timer.proto

package timer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Timer service

func NewTimerEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Timer service

type TimerService interface {
	Wait(ctx context.Context, in *TimerRequest, opts ...client.CallOption) (*TimerResponse, error)
}

type timerService struct {
	c    client.Client
	name string
}

func NewTimerService(name string, c client.Client) TimerService {
	return &timerService{
		c:    c,
		name: name,
	}
}

func (c *timerService) Wait(ctx context.Context, in *TimerRequest, opts ...client.CallOption) (*TimerResponse, error) {
	req := c.c.NewRequest(c.name, "Timer.Wait", in)
	out := new(TimerResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Timer service

type TimerHandler interface {
	Wait(context.Context, *TimerRequest, *TimerResponse) error
}

func RegisterTimerHandler(s server.Server, hdlr TimerHandler, opts ...server.HandlerOption) error {
	type timer interface {
		Wait(ctx context.Context, in *TimerRequest, out *TimerResponse) error
	}
	type Timer struct {
		timer
	}
	h := &timerHandler{hdlr}
	return s.Handle(s.NewHandler(&Timer{h}, opts...))
}

type timerHandler struct {
	TimerHandler
}

func (h *timerHandler) Wait(ctx context.Context, in *TimerRequest, out *TimerResponse) error {
	return h.TimerHandler.Wait(ctx, in, out)
}
